fun main() {
    println("Квадрат:")
    var square = Square(4,3,4)
    println("Исходные параметры: $square")
    square.rotate(RotateDirection.Clockwise, 3, -3)
    println("Поворот из исходного положения по часовой стрелке в точку (3, -3): $square")
    square = Square(4,3,4)
    square.rotate(RotateDirection.CounterClockwise, 3, -3)
    println("Поворот из исходного положения против часовой стрелке в точку (3, -3): $square")
    square.resize(10)
    println("Увеличение в 10 раз: $square")
    square.move(5, 5)
    println("Смещение на +5 по оси х и +5 по оси у: $square")
    println("Круг:")
    var circle = Circle(4,3,4)
    println("Исходные параметры: $circle")
    circle.rotate(RotateDirection.Clockwise, 3, -3)
    println("Поворот из исходного положения по часовой стрелке в точку (3, -3): $circle")
    circle = Circle(4,3,4)
    circle.rotate(RotateDirection.CounterClockwise, 3, -3)
    println("Поворот из исходного положения против часовой стрелке в точку (3, -3): $circle")
    circle.resize(10)
    println("Увеличение в 10 раз: $circle")
    circle.move(5, 5)
    println("Смещение на +5 по оси х и +5 по оси у: $circle")
    println("Прямоугольник:")
    var rect = Rect(4,3,4,2)
    println("Исходные параметры: $rect")
    rect.rotate(RotateDirection.Clockwise, 3, -3)
    println("Поворот из исходного положения по часовой стрелке в точку (3, -3): $rect")
    rect = Rect(4,3,4,2)
    rect.rotate(RotateDirection.CounterClockwise, 3, -3)
    println("Поворот из исходного положения против часовой стрелке в точку (3, -3): $rect")
    rect.resize(10)
    println("Увеличение в 10 раз: $rect")
    rect.move(5, 5)
    println("Смещение на +5 по оси х и +5 по оси у: $rect")
}